// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcsQ6a6Ab40doLBQWP9_n7Az6iUjR3Ng0',
    appId: '1:27937037192:android:8ad9f93175fc38f001b83d',
    messagingSenderId: '27937037192',
    projectId: 'todo-app-7bda9',
    storageBucket: 'todo-app-7bda9.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxq0sejpw3O8myqYrsJSnlyCsjDE2Zggg',
    appId: '1:27937037192:web:7dc9c2f8e366c2d401b83d',
    messagingSenderId: '27937037192',
    projectId: 'todo-app-7bda9',
    authDomain: 'todo-app-7bda9.firebaseapp.com',
    storageBucket: 'todo-app-7bda9.appspot.com',
    measurementId: 'G-4Y14HLQBPD',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxq0sejpw3O8myqYrsJSnlyCsjDE2Zggg',
    appId: '1:27937037192:web:2b2b600d9969c4d301b83d',
    messagingSenderId: '27937037192',
    projectId: 'todo-app-7bda9',
    authDomain: 'todo-app-7bda9.firebaseapp.com',
    storageBucket: 'todo-app-7bda9.appspot.com',
    measurementId: 'G-WLE3NQHNFV',
  );

}